// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZ-H-xDRNUa15GKodDbVnt777UsvEHlg',
    appId: '1:652474498041:web:0c20cff40da716b4089b28',
    messagingSenderId: '652474498041',
    projectId: 'movie-db-app-34d7e',
    authDomain: 'movie-db-app-34d7e.firebaseapp.com',
    storageBucket: 'movie-db-app-34d7e.appspot.com',
    measurementId: 'G-DVWDWGK8K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCDUOrD58gog4FGGw9JL5S5mJLZudP-k',
    appId: '1:652474498041:android:aa43e336927bf84e089b28',
    messagingSenderId: '652474498041',
    projectId: 'movie-db-app-34d7e',
    storageBucket: 'movie-db-app-34d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdy7hZjD-RVVM0OmCEmxdCpKx-lTR2jc',
    appId: '1:652474498041:ios:7cc3908b86fa2ddb089b28',
    messagingSenderId: '652474498041',
    projectId: 'movie-db-app-34d7e',
    storageBucket: 'movie-db-app-34d7e.appspot.com',
    iosBundleId: 'com.example.movieDbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATdy7hZjD-RVVM0OmCEmxdCpKx-lTR2jc',
    appId: '1:652474498041:ios:8c6f8bb169104a93089b28',
    messagingSenderId: '652474498041',
    projectId: 'movie-db-app-34d7e',
    storageBucket: 'movie-db-app-34d7e.appspot.com',
    iosBundleId: 'com.example.movieDbApp.RunnerTests',
  );
}
